name: Development actions

on:
  push:
    branches: ["development"]

jobs:
  releaseGooglePlaces:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish Places to Sonatype
        run:  >
          ./gradlew :places:publishAllPublicationsToMavenCentral 
          -Penv=dev
          -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
          -PsigningInMemoryKey=${{ secrets.SIGNING_KEY }}
          -PsigningInMemoryKeyPassword=${{ secrets.SIGNING_PASSWORD }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
